class DefineTypeUnpauredSpin(object):
    level = 0
    sub_level = ''
    j = 0
    energy_level = 0
    parity = 0

    def __init__(self, nucleons):
        if 1 <= nucleons <=2:
            self.level = 0
            self.sub_level = '1s'
            self.j = 1./2.
            self.energy_level = 1 # 1 para nivel inferior, 2 para nivel superior
        elif 3 <= nucleons <= 6:
            self.level = 1
            self.sub_level = '1p'
            self.j = 3./2.
            self.energy_level = 1
        elif nucleons >= 7 and nucleons <=8:
            self.level = 1
            self.sub_level = '1p'
            self.j = 1./2.
            self.energy_level = 2
        elif nucleons >= 9 and nucleons <=14:
            self.level = 2
            self.sub_level = '1d'
            self.j = 5./2.
            self.energy_level = 1
        elif nucleons >= 15 and nucleons <=16:
            self.level = 0
            self.sub_level = '2s'
            self.j = 1./2.
            self.energy_level = 1
        elif nucleons >= 17 and nucleons <=20:
            self.level = 2
            self.sub_level = '1d'
            self.j = 3./2.
            self.energy_level = 2
        elif nucleons >= 21 and nucleons <=28:
            self.level = 3
            self.sub_level = '1f'
            self.j = 7./2.
            self.energy_level = 1
        elif nucleons >= 29 and nucleons <=32:
            self.level = 1
            self.sub_level = '2p'
            self.j = 3./2.
            self.energy_level = 1
        elif nucleons >= 33 and nucleons <=38:
            self.level = 3
            self.sub_level = '1f'
            self.j = 5./2.
            self.energy_level = 2
        elif nucleons in(39,40):
            self.level = 1
            self.sub_level = '2p'
            self.j = 1./2.
            self.energy_level = 2
        elif nucleons in(41,50):
            self.level = 4
            self.sub_level = '1g'
            self.j = 9./2.
            self.energy_level = 1
        elif nucleons in(51,58):
            self.level = 4
            self.sub_level = '1g'
            self.j = 7./2.
            self.energy_level = 2
        elif nucleons in(59,64):
            self.level = 2
            self.sub_level = '2d'
            self.j = 5./2.
            self.energy_level = 1
        elif nucleons in(65,68):
            self.level = 2
            self.sub_level = '2d'
            self.j = 3./2.
            self.energy_level = 2
        elif nucleons in(69,70):
            self.level = 0
            self.sub_level = '3s'
            self.j = 1./2.
            self.energy_level = 1
        elif nucleons in(71,82):
            self.level = 5
            self.sub_level = '1h'
            self.j = 11./2.
            self.energy_level = 1
        elif nucleons in(83,92):
            self.level = 5
            self.sub_level = '1h'
            self.j = 9./2.
            self.energy_level = 2
        elif nucleons in(93,100):
            self.level = 3
            self.sub_level = '2f'
            self.j = 7./2.
            self.energy_level = 1
        elif nucleons in(101,104):
            self.level = 1
            self.sub_level = '3p'
            self.j = 3./2.
            self.energy_level = 1
        elif nucleons in(105,110):
            self.level = 3
            self.sub_level = '2f'
            self.j = 5./2.
            self.energy_level = 2
        elif nucleons in(111,112):
            self.level = 1
            self.sub_level = '3p'
            self.j = 1./2.
            self.energy_level = 2
        elif nucleons in(113,126):
            self.level = 6
            self.sub_level = '1i'
            self.j = 13./2.
            self.energy_level = 1
        elif nucleons in(127,136):
            self.level = 4
            self.sub_level = '2g'
            self.j = 9./2.
            self.energy_level = 1
        elif nucleons in(137,142):
            self.level = 2
            self.sub_level = '3d'
            self.j = 5./2.
            self.energy_level = 1
        elif nucleons in(143,154):
            self.level = 6
            self.sub_level = '1i'
            self.j = 11./2.
            self.energy_level = 2
        elif nucleons in(155,162):
            self.level = 4
            self.sub_level = '2g'
            self.j = 7./2.
            self.energy_level = 2
        elif nucleons in(163,164):
            self.level = 0
            self.sub_level = '4s'
            self.j = 1./2.
            self.energy_level = 1
        elif nucleons in(165,168):
            self.level = 2
            self.sub_level = '3d'
            self.j = 3./2.
            self.energy_level = 2
        elif nucleons in(169,184):
            self.level = 7
            self.sub_level = '1j'
            self.j = 15./2.
            self.energy_level = 1
        self.parity = (-1)**self.level